export const SAVE_ADVERTISEMENT_DATA = 'SAVE_ADVERTISEMENT_DATA'
export const SAVE_KIND_DATA = 'SAVE_KIND_DATA'
export const SAVE_SHOPLIST_DATA = 'SAVE_SHOPLIST_DATA'
export const UPDATE_SHOPLIST_DATA = 'UPDATE_SHOPLIST_DATA'
